### ISSUE TITLE
Need a cross platform script

### ISSUE THREAD

**Issue by hYdos** [BadlionModdingGroup/bomf#11]
need new script to map which works on other os'es

**Comment by hYdos** [comment]
im currently working on a gradle plugin. give me a bit and ill have this done

**Comment by BoogieMonster1O1** [comment]
copy/paste the one from yarn

**Comment by hYdos** [comment]
no, thats also not how it works

**Comment by BoogieMonster1O1** [comment]
why not

**Comment by hYdos** [comment]
its not how it works

**Comment by hYdos** [comment]
implemented with gradle
